[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "shifts_generator"
version = "0.1.0"
description = "Shift generator"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]